spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:54320/poi
    username: poi_dev
    password: dev_pass
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    show-sql: true
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: 1.create_tables.sql

world:
  poi:
    security:
      enable: true
    jwt:
      secret: muchsecret
server:
  servlet:
    context-path: /api